/**
 * exporter.js
 * Exports the heart model as OBJ or STL, and captures labeled screenshots.
 */

/** Convert a BufferGeometry to OBJ format string */
function geometryToOBJ(mesh, objLines, mtlLines, meshIndex) {
  const geo = mesh.geometry.clone();
  geo.applyMatrix4(mesh.matrixWorld);

  const pos = geo.attributes.position;
  const nor = geo.attributes.normal;
  const idx = geo.index;

  const vOffset = objLines.filter(l => l.startsWith('v ')).length + 1;

  objLines.push(`\n# ${mesh.name}`);
  objLines.push(`g ${mesh.name.replace(/\s+/g, '_')}`);
  objLines.push(`usemtl mat_${meshIndex}`);

  // Vertices
  for (let i = 0; i < pos.count; i++) {
    objLines.push(`v ${pos.getX(i).toFixed(5)} ${pos.getY(i).toFixed(5)} ${pos.getZ(i).toFixed(5)}`);
  }
  // Normals
  if (nor) {
    for (let i = 0; i < nor.count; i++) {
      objLines.push(`vn ${nor.getX(i).toFixed(5)} ${nor.getY(i).toFixed(5)} ${nor.getZ(i).toFixed(5)}`);
    }
  }
  // Faces
  if (idx) {
    for (let i = 0; i < idx.count; i += 3) {
      const a = idx.getX(i)   + vOffset;
      const b = idx.getX(i+1) + vOffset;
      const c = idx.getX(i+2) + vOffset;
      if (nor) {
        objLines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
      } else {
        objLines.push(`f ${a} ${b} ${c}`);
      }
    }
  } else {
    for (let i = 0; i < pos.count; i += 3) {
      const a = i   + vOffset;
      const b = i+1 + vOffset;
      const c = i+2 + vOffset;
      objLines.push(`f ${a} ${b} ${c}`);
    }
  }

  // Material
  const color = mesh.material.color;
  mtlLines.push(`\nnewmtl mat_${meshIndex}`);
  mtlLines.push(`Kd ${color.r.toFixed(4)} ${color.g.toFixed(4)} ${color.b.toFixed(4)}`);
  mtlLines.push(`d ${mesh.material.opacity.toFixed(4)}`);
}

export function exportOBJ(heartGroup) {
  const objLines = ['# 3D Human Heart — Anatomical Model', '# Generated by Heart Visualizer', 'mtllib heart.mtl'];
  const mtlLines = ['# Heart Materials'];
  let idx = 0;

  heartGroup.traverse(child => {
    if (child.isMesh) {
      geometryToOBJ(child, objLines, mtlLines, idx++);
    }
  });

  _download('heart.obj', objLines.join('\n'));
  _download('heart.mtl', mtlLines.join('\n'));
}

/** STL binary export */
export function exportSTL(heartGroup) {
  const meshes = [];
  heartGroup.traverse(c => { if (c.isMesh) meshes.push(c); });

  let triCount = 0;
  meshes.forEach(m => {
    const geo = m.geometry;
    triCount += geo.index ? geo.index.count / 3 : geo.attributes.position.count / 3;
  });

  const buf = new ArrayBuffer(84 + triCount * 50);
  const view = new DataView(buf);

  // Header (80 bytes)
  const header = '3D Human Heart Anatomical Model - Heart Visualizer';
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }
  view.setUint32(80, triCount, true);

  let offset = 84;
  meshes.forEach(mesh => {
    const geo = mesh.geometry.clone();
    geo.applyMatrix4(mesh.matrixWorld);
    if (!geo.attributes.normal) geo.computeVertexNormals();

    const pos = geo.attributes.position;
    const nor = geo.attributes.normal;
    const idx = geo.index;

    const writeTri = (ai, bi, ci) => {
      // Normal (average)
      const nx = (nor.getX(ai) + nor.getX(bi) + nor.getX(ci)) / 3;
      const ny = (nor.getY(ai) + nor.getY(bi) + nor.getY(ci)) / 3;
      const nz = (nor.getZ(ai) + nor.getZ(bi) + nor.getZ(ci)) / 3;
      view.setFloat32(offset,    nx, true); offset += 4;
      view.setFloat32(offset,    ny, true); offset += 4;
      view.setFloat32(offset,    nz, true); offset += 4;
      [ai, bi, ci].forEach(i => {
        view.setFloat32(offset, pos.getX(i), true); offset += 4;
        view.setFloat32(offset, pos.getY(i), true); offset += 4;
        view.setFloat32(offset, pos.getZ(i), true); offset += 4;
      });
      view.setUint16(offset, 0, true); offset += 2;
    };

    if (idx) {
      for (let i = 0; i < idx.count; i += 3) writeTri(idx.getX(i), idx.getX(i+1), idx.getX(i+2));
    } else {
      for (let i = 0; i < pos.count; i += 3) writeTri(i, i+1, i+2);
    }
  });

  const blob = new Blob([buf], { type: 'application/octet-stream' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'heart.stl'; a.click();
  URL.revokeObjectURL(url);
}

/** Screenshot with label overlay */
export function captureScreenshot(renderer, camera, scene, label = 'Heart Visualization') {
  renderer.render(scene, camera);
  const canvas = renderer.domElement;

  // Composite onto a 2D canvas with label
  const out = document.createElement('canvas');
  out.width  = canvas.width;
  out.height = canvas.height;
  const ctx = out.getContext('2d');
  ctx.drawImage(canvas, 0, 0);

  // Label
  ctx.fillStyle = 'rgba(10,10,22,0.7)';
  ctx.fillRect(0, out.height - 50, out.width, 50);
  ctx.fillStyle = '#ff6b6b';
  ctx.font = 'bold 18px Segoe UI, sans-serif';
  ctx.fillText('3D Human Heart — Anatomical Visualization', 16, out.height - 18);
  ctx.fillStyle = '#aaa';
  ctx.font = '13px Segoe UI, sans-serif';
  ctx.fillText(label, 16, out.height - 36);

  out.toBlob(blob => {
    const url = URL.createObjectURL(blob);
    const a   = document.createElement('a');
    a.href = url; a.download = 'heart_screenshot.png'; a.click();
    URL.revokeObjectURL(url);
  });
}

function _download(filename, text) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
